config/routes.rb
LiveSign::Application.routes.draw do
  
  resources :propositions, :only => [:show, :index] do
    get "signature_complete", on: :member

    resources :signatures, :only => [:new, :create, :index], :controller => 'propositions/signatures' do
      member do
        put :accept
        put :reject
      end
    end

    resources :users, :except => [:index, :destroy], :controller => 'propositions/users'
    resources :videos, :only => [:new, :create], :controller => 'propositions/videos'
  end

  get '/terms_of_service' => 'pages#terms_of_service', :as => :terms_of_service

  root :to => 'home#index'

  get '/demo' => 'home#demo', :as => :demo

  get '/contact_us' => 'pages#contact_us', :as => :contact_us

end

app/models/proposition.rb
class Proposition < ActiveRecord::Base
  #attr_accessible :title, :body
  belongs_to :user
  has_many :signatures

  before_save :title_to_slug

  def title_to_slug
    self.slug = ActiveSupport::Inflector.transliterate(self.title).downcase.gsub(/[^a-z0-9 ]/, ' ').strip.gsub(/[ ]+/, '-')
  end

end

app/models/signature.rb
class Signature < ActiveRecord::Base
  belongs_to :user
  belongs_to :proposition

  validates_uniqueness_of :user_id, :scope => [:proposition_id]
  validates_presence_of :user_id, :proposition_id

  attr_accessible :user, :proposition, :data, :opentok_archive_id, :verified
end

app/controllers/propositions/base_controller.rb
class Propositions::BaseController < ApplicationController
  
  before_filter :get_proposition

private  
  
  def get_proposition
    @proposition = Proposition.find_by_slug(params[:proposition_id])
  end
  
  def get_user
    if session[:user_id].blank?
      @user = User.find_by_id(params[:user_id])
    else
      @user = User.find_by_id(session[:user_id])
    end
  end

  def get_signature
    @signature = Signature.where(proposition_id: params[:proposition_id], user_id: params[:user_id], id: params[:id]).first
  end

end

app/controllers/propositions/signatures_controller.rb
class Propositions::SignaturesController < Propositions::BaseController

  before_filter :get_user, except: [:index, :accept, :reject]

  def new
    @signature = Signature.new
  end

  def edit
  end

  def update
  end

  def create
    @signature = Signature.where(user_id: @user.id, proposition_id: @proposition.id).first || Signature.new(user: @user, proposition: @proposition)
    @signature.data = params[:data]

    if @signature.save
      respond_to do |format|
        format.json { render :json, {:success => true} }
        format.html { redirect_to new_proposition_video_path(@proposition.slug, :user_id => @user, :signature_id => @signature)}
      end

      return
    end

    respond_to do |format|
      format.json { render :json, {:success => false, :errors => @signature.errors } }
      format.html {
        flash[:error] = errors_to_string(@signature.errors)
        render :action => :new
      }
    end
  end

  def index
    @proposition = Proposition.find_by_slug(params[:proposition_id])
    @signatures = @proposition.signatures.includes(:user)
  end

  def accept
    @signature = Signature.find(params[:id])
    @signature.verified = true

    if @signature.save
      flash[:notice] = "Signature has been approved"
    end

    resond_with(@signature, location: signatures_path)
  end

  def reject
    @signature = Signature.find(params[:id])
    @signature.verified = false

    if @signature.save
      flash[:notice] = "Signature has been rejected"
    end

    resond_with(@signature, location: signatures_path)
  end
end

app/controllers/propositions/users_controller.rb
class Propositions::UsersController < Propositions::BaseController

  before_filter :get_user, :only => [:edit, :update]

  def new
    @user = User.new
  end
  
  def edit
    # edit.html.erb
  end

  def update
    if @user.update_attributes(params[:user])
     respond_to do |format|
        format.json { render :json, {:success => true} }
        format.html { redirect_to new_proposition_signature_path(@proposition.slug, :user_id => @user)}
      end
    else
      respond_to do |format|
        format.json { render :json, {:success => false, :errors => @user.errors } }
        format.html do
          flash[:error] = errors_to_string(@user.errors)
          render :action => :edit
        end
      end
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id

      respond_to do |format|
        format.json { render :json, {:success => true} }
        format.html { redirect_to new_proposition_signature_path(@proposition.slug, :user_id => @user)}
      end
    else
      respond_to do |format|
        format.json { render :json, {:success => false, :errors => @user.errors } }
        format.html do
          flash[:error] = errors_to_string(@user.errors)
          render :action => :new
        end
      end
    end
  end

private

  def get_user
    @user = User.find_by_id(params[:id])
  end

end

app/controllers/propositions/videos_controller.rb
class Propositions::VideosController < Propositions::BaseController

  before_filter :get_proposition, :get_user
  before_filter :get_signature, except: :index
  before_filter :get_client_config, :only => [:new]

  def new
    #
  end

  def create
    if params[:opentok_archive_id].present? && @signature.update_attribute(:opentok_archive_id, params[:opentok_archive_id])
      redirect_to signature_complete_proposition_path(@proposition.slug)
    else
      get_client_config
      flash[:error] = "Unable to save recorded video"
      render :action => :new
    end
  end
  
private

  def get_client_config
    @client_config = { opentok_api_key: Rails.configuration.opentok.api_key }
    @client_config[:opentok_session_id] = opentok_session
    @client_config[:opentok_auth_token] = opentok_token(session_id: @client_config[:opentok_session_id])
  end

  def get_signature
    @signature = Signature.find(params[:signature_id].to_i)
  end

end

app/controllers/propositions_controller.rb
class PropositionsController < ApplicationController

  before_filter :get_proposition, :only => [:show, :signature_complete]

  def index
    @propositions = Proposition.paginate(:page => params[:page])
  end

  def show
    @proposition = Proposition.find_by_slug(params[:id]) || Proposition.find(params[:id])
  end

  def signature_complete
    #
  end

private

  def get_proposition
    @proposition = Proposition.find_by_slug(params[:id])
  end

end

app/helpers/propositions/users_helper.rb
module Propositions::UsersHelper
end

app/helpers/propositions/videos_helper.rb
module Propositions::VideosHelper
end

app/helpers/propositions_helper.rb
module PropositionsHelper

  def sign_button
    content_tag :a, :href => new_proposition_user_path(@proposition.slug) do
      content_tag :div, 'LiveSign', :class => 'live_sign_button'
    end
  end

end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/propositions/signatures/index.html.erb
<% content_for(:head) do %>
<%= javascript_include_tag "jquery.mobile" %>
<%= stylesheet_link_tag "jquery.mobile" %>
<% end %>

<% content_for(:main_content) do %>
<div class="prop_container">
<div class="custom_scroll_bar wants_content retained">
<div class="native">
<div class="content">

<form id="signature_list">
	<div class="header">
		<h1 class="title"><%= @proposition.title %></h1>
	</div>

	<ol class="signatures">
		<% @signatures.each do |signature| %>
		<li class="signature">
			<div class="archive" <%= signature.opentok_archive_id? ? "id=archive-#{signature.opentok_archive_id}" : nil %>>
				<img src="http://placehold.it/120x120"/>
			</div>

			<div class="user sub_content" id="user-<%= signature.user.id %>">
				<%= signature.user.name %><br/>
				<%= signature.user.street_address %><br/>
				<%= signature.user.city %><br/>
				<%= signature.user.zip_code %><br/>
				<%= signature.user.phone %><br/>
				<%= signature.user.email_address %>
			</div>

			<div class="metadata sub_content grey">
				Signed <%= l(signature.created_at, format: "%b %e %Y %l:%M%p") %>
			</div>

			<%= select_tag(
				"signatures[signature_attributes][#{signature.id}]",
				options_for_select("Reject" => false, "Accept" => true),
				:class => :verified, "data-role" => :slider) %>
		</li>
		<% end %>
	</ol>

	<div class="footer"></div>
</form>

</div>
</div>
</div>
</div>
<% end %>

app/views/propositions/signatures/new.html.erb
<% content_for :head do %>
  
  <%= javascript_include_tag "signature-pad/build/jquery.signaturepad.min.js"%>

  <script>
    $(document).ready(function() {
      var options = {
        drawOnly: true,
        defaultAction: 'drawIt',
        validateFields: false,
        output: '.data'
      };
      $('.sigPad').signaturePad(options);
    });
  </script>

<% end %>

<% content_for :main_content do %>

<div class="progressbar progressbar03-blue">
    <div class="progressbar-inner">
    </div>
</div>
    <%= form_for :signature, :url => proposition_signatures_path(@proposition.slug, :user_id => @user.id), :html => {:class => 'sigPad form'} do |f| %>

      <div class="centered_container">

        <h1 class="title signature_title">Sign Your Name</h1>
        <h2 class="sub_title signature_sub_title">Use a finger or a mouse<br/>inside the box below.</h2>


        <div class="sig sigWrapper">
          <canvas class="pad <%= 'error' if @signature.errors[:data] %>" width="834px" height="250px"></canvas>
          <input type="hidden" name="data" class="data">
        </div>

      </div>

      <div class="clearButton button"><a href="#clear" class="grey">Clear</a></div>

    <% end %>

<% end %>

<% content_for :controls do %>

  <div class="left_content">
    <%= link_to "Back", edit_proposition_user_path(@proposition.slug, @user), :class => "gray_button button"%>
  </div>

  <div class="middle_button_container">
    <button href="#" class="red_button button" onClick="$('.form').submit();">
      Next <%= image_tag "arrow_white.png", :class => "next_image button_image" %>
    </button>
  </div>

  <!-- <div class="right_content">
    <a href="#" class="gray_button button">Cancel</a>
  </div> -->

<% end %>