config/routes.rb
LiveSign::Application.routes.draw do
  
  resources :propositions, :only => [:show, :index] do
    get "signature_complete", on: :member

    resources :signatures, :only => [:new, :create, :index], :controller => 'propositions/signatures' do
      member do
        put :accept
        put :reject
      end
    end

    resources :users, :except => [:index, :destroy], :controller => 'propositions/users'
    resources :videos, :only => [:new, :create], :controller => 'propositions/videos'
  end

  get '/terms_of_service' => 'pages#terms_of_service', :as => :terms_of_service

  root :to => 'home#index'

  get '/demo' => 'home#demo', :as => :demo

  get '/contact_us' => 'pages#contact_us', :as => :contact_us

end

app/models/proposition.rb
class Proposition < ActiveRecord::Base
  #attr_accessible :title, :body
  belongs_to :user
  has_many :signatures

  before_save :title_to_slug

  def title_to_slug
    self.slug = ActiveSupport::Inflector.transliterate(self.title).downcase.gsub(/[^a-z0-9 ]/, ' ').strip.gsub(/[ ]+/, '-')
  end

end

app/models/user.rb
# t.string   "phone"
# t.string   "street_address"
# t.string   "email_address"
# t.string   "city"
# t.string   "state"
# t.string   "name"
# t.string   "zip_code"
# t.string   "tos_acceptance"
class User < ActiveRecord::Base

  has_many :signatures

  validates :name, :email_address, :street_address, :city, :zip_code, :phone, :tos_acceptance, presence: true

  attr_accessible :name, :email_address, :street_address, :city, :zip_code, :phone, :tos_acceptance

end

app/controllers/propositions/base_controller.rb
class Propositions::BaseController < ApplicationController
  
  before_filter :get_proposition

private  
  
  def get_proposition
    @proposition = Proposition.find_by_slug(params[:proposition_id])
  end
  
  def get_user
    if session[:user_id].blank?
      @user = User.find_by_id(params[:user_id])
    else
      @user = User.find_by_id(session[:user_id])
    end
  end

  def get_signature
    @signature = Signature.where(proposition_id: params[:proposition_id], user_id: params[:user_id], id: params[:id]).first
  end

end

app/controllers/propositions/signatures_controller.rb
class Propositions::SignaturesController < Propositions::BaseController

  before_filter :get_user, except: [:index, :accept, :reject]

  def new
    @signature = Signature.new
  end

  def edit
  end

  def update
  end

  def create
    @signature = Signature.where(user_id: @user.id, proposition_id: @proposition.id).first || Signature.new(user: @user, proposition: @proposition)
    @signature.data = params[:data]

    if @signature.save
      respond_to do |format|
        format.json { render :json, {:success => true} }
        format.html { redirect_to new_proposition_video_path(@proposition.slug, :user_id => @user, :signature_id => @signature)}
      end

      return
    end

    respond_to do |format|
      format.json { render :json, {:success => false, :errors => @signature.errors } }
      format.html {
        flash[:error] = errors_to_string(@signature.errors)
        render :action => :new
      }
    end
  end

  def index
    @proposition = Proposition.find_by_slug(params[:proposition_id])
    @signatures = @proposition.signatures.includes(:user)
  end

  def accept
    @signature = Signature.find(params[:id])
    @signature.verified = true

    if @signature.save
      flash[:notice] = "Signature has been approved"
    end

    resond_with(@signature, location: signatures_path)
  end

  def reject
    @signature = Signature.find(params[:id])
    @signature.verified = false

    if @signature.save
      flash[:notice] = "Signature has been rejected"
    end

    resond_with(@signature, location: signatures_path)
  end
end

app/controllers/propositions/users_controller.rb
class Propositions::UsersController < Propositions::BaseController

  before_filter :get_user, :only => [:edit, :update]

  def new
    @user = User.new
  end
  
  def edit
    # edit.html.erb
  end

  def update
    if @user.update_attributes(params[:user])
     respond_to do |format|
        format.json { render :json, {:success => true} }
        format.html { redirect_to new_proposition_signature_path(@proposition.slug, :user_id => @user)}
      end
    else
      respond_to do |format|
        format.json { render :json, {:success => false, :errors => @user.errors } }
        format.html do
          flash[:error] = errors_to_string(@user.errors)
          render :action => :edit
        end
      end
    end
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id

      respond_to do |format|
        format.json { render :json, {:success => true} }
        format.html { redirect_to new_proposition_signature_path(@proposition.slug, :user_id => @user)}
      end
    else
      respond_to do |format|
        format.json { render :json, {:success => false, :errors => @user.errors } }
        format.html do
          flash[:error] = errors_to_string(@user.errors)
          render :action => :new
        end
      end
    end
  end

private

  def get_user
    @user = User.find_by_id(params[:id])
  end

end

app/controllers/propositions/videos_controller.rb
class Propositions::VideosController < Propositions::BaseController

  before_filter :get_proposition, :get_user
  before_filter :get_signature, except: :index
  before_filter :get_client_config, :only => [:new]

  def new
    #
  end

  def create
    if params[:opentok_archive_id].present? && @signature.update_attribute(:opentok_archive_id, params[:opentok_archive_id])
      redirect_to signature_complete_proposition_path(@proposition.slug)
    else
      get_client_config
      flash[:error] = "Unable to save recorded video"
      render :action => :new
    end
  end
  
private

  def get_client_config
    @client_config = { opentok_api_key: Rails.configuration.opentok.api_key }
    @client_config[:opentok_session_id] = opentok_session
    @client_config[:opentok_auth_token] = opentok_token(session_id: @client_config[:opentok_session_id])
  end

  def get_signature
    @signature = Signature.find(params[:signature_id].to_i)
  end

end

app/controllers/propositions_controller.rb
class PropositionsController < ApplicationController

  before_filter :get_proposition, :only => [:show, :signature_complete]

  def index
    @propositions = Proposition.paginate(:page => params[:page])
  end

  def show
    @proposition = Proposition.find_by_slug(params[:id]) || Proposition.find(params[:id])
  end

  def signature_complete
    #
  end

private

  def get_proposition
    @proposition = Proposition.find_by_slug(params[:id])
  end

end

app/helpers/propositions/users_helper.rb
module Propositions::UsersHelper
end

app/helpers/propositions/videos_helper.rb
module Propositions::VideosHelper
end

app/helpers/propositions_helper.rb
module PropositionsHelper

  def sign_button
    content_tag :a, :href => new_proposition_user_path(@proposition.slug) do
      content_tag :div, 'LiveSign', :class => 'live_sign_button'
    end
  end

end

app/views/propositions/users/_form.html.erb
<%= form.text_field :name, :placeholder => "Name", :class => "name_field input_text" %>
<%= form.text_field :email_address, :placeholder => "Email", :class => "email_address_field input_text" %>
<%= form.text_field :street_address, :placeholder => "Street Address", :class => "street_address_field input_text" %>
<%= form.text_field :city, :placeholder => "City", :class => "city_field input_text" %>
<%= form.text_field :zip_code, :placeholder => "Zipcode", :class => "zipcode_field input_text" %>
<%= form.text_field :phone, :placeholder => "Phone", :class => "phone_field input_text" %>
<div class="tos_container">
  <%= form.check_box :tos_acceptance, :id => "tos_acceptance" %>
  <span class="input_text checkbox_label" onclick="$('#tos_acceptance').click();$(this).toggleClass('checked');">
    I agree to the LiveView <%= link_to "terms of service", terms_of_service_path(:proposition => @proposition.slug) %>.
  </span>
</div>

app/views/propositions/users/edit.html.erb
<% content_for :main_content do %>

  <div class="centered_container">

    <h1 class="title user_title">Enter in your information</h1>

    <div class="form_container">

      <%= form_for @user, :url => proposition_user_path(@proposition.slug, @user), :html => {:method => :put, :class => "form"} do |f| %>
        <%= render :partial => "form", :object => f %>
      <% end %>

    </div>

  </div>

<% end %>

<% content_for :controls do %>

  <div class="left_content">
    <%= link_to "Back", proposition_path(@proposition.slug), :class => "gray_button button"%>
  </div>

  <div class="middle_button_container">
    <button href="#" class="red_button button" onClick="$('.form').submit();">
      Next <%= image_tag "arrow_white.png", :class => "next_image button_image" %>
    </button>
  </div>
<% end %>

app/views/propositions/users/new.html.erb
<% content_for :main_content do %>
<div class="progressbar progressbar02-blue">
    <div class="progressbar-inner">
    </div>
</div>
  <div class="centered_container">

    <h1 class="title user_title">Enter in your information</h1>

    <div class="form_container">

      <%= form_for @user, :url => proposition_users_path(@proposition.slug), :html => {:class => "form"} do |f| %>
        <%= render :partial => "form", :object => f %>
      <% end %>

    </div>

  </div>

<% end %>

<% content_for :controls do %>
  <div class="left_content">
    <%= link_to "Back", proposition_path(@proposition.slug), :class => "gray_button button"%>
  </div>

  <div class="middle_button_container">
    <button href="#" class="red_button button" onClick="$('.form').submit();">
      Next <%= image_tag "arrow_white.png", :class => "next_image button_image" %>
    </button>
  </div>
<% end %>